Develop
xZodiac2/VK_Friends pull request #1
Opened 2024-04-07 21:30 UTC by xZodiac2

2024-04-09 14:32 UTC, gbixahue requested changes

2024-04-09 14:32 UTC, gbixahue commented on app/src/main/java/com/ilya/vkfriends/MainActivity.kt
> +                    }
Трудно читается.
Не стоит передавать чувствительную информацию для таких случаев. Можно, например: if (flag == NotAuthorized)
Думаю, что для твоего случая лучше будет сделать onUnauthorizedCallback в accessTokenManager.

2024-04-09 14:32 UTC, gbixahue commented on core/src/main/java/com/ilya/core/appCommon/AccessTokenManager.kt
> +            listener.onOperation(getAccessTokenValue(notify = false))
Нужно сначала получить токен, а потом делать обработку в цикле

2024-04-09 14:32 UTC, gbixahue commented on core/src/main/java/com/ilya/core/appCommon/AccessTokenManager.kt
> +    private fun notifyListeners() {
Возможна проблема ConcurrentModificationException

2024-04-09 14:32 UTC, gbixahue commented on core/src/main/java/com/ilya/core/appCommon/AccessTokenManager.kt
> +        accessTokenOperationsListeners += accessTokenOperationsListener
Возможна проблема ConcurrentModificationException

2024-04-09 14:32 UTC, gbixahue commented on core/src/main/java/com/ilya/core/appCommon/AccessTokenManager.kt
> +        accessTokenOperationsListeners -= accessTokenOperationsListener
Возможна проблема ConcurrentModificationException

2024-04-09 14:32 UTC, gbixahue commented on app/src/main/java/com/ilya/vkfriends/navigation/NavigationTransition.kt
> +    val popEnterTransition: (AnimatedContentTransitionScope<NavBackStackEntry>.() -> EnterTransition?)? = enterTransition,
Ты уверен, что будет правильная анимация при твоем подходе?
https://stackoverflow.com/questions/40878819/what-is-the-difference-between-enter-exit-and-popenter-popexit-animations

2024-04-09 14:32 UTC, gbixahue commented on core/src/main/java/com/ilya/core/basicComposables/Composables.kt
> +fun UserCard(
`UserCard` не относится к базовым

2024-04-09 14:32 UTC, gbixahue commented on core/src/main/java/com/ilya/core/commonDi/SharedPreferencesModule.kt
> +    private const val SHARED_PREFERENCES_NAME = "com.ilya.vkfriends.accessToken"
Как-то расточительно целое хранилище для одной переменной использовать.
У тебя SharedPreferences выступает синглтоном для всего проекта, а если ты захочешь дополнительную инфу хранить в шардах - будешь новый инстанс создавать в модуле?

2024-04-09 14:32 UTC, gbixahue commented on core/src/main/java/com/ilya/core/util/Logs.kt
> +    Log.d("throwable", "Cause: ${exception.cause}")
```
Log.d("throwable", "Exception: $exception")
Log.d("throwable", "Message: ${exception.message}")
```
Это почти дубликаты.

`"Exception: $exception"` вызовет Throwable.toString()

2024-04-09 14:32 UTC, gbixahue commented on feature/friendsView/src/main/res/values-ru/strings.xml
> +    <string name="error_no_internet">Не получается получить список друзей. Проверьте подключение к интернету и попробуйте снова</string>
`error_no_internet` - название должно говорит об ошибке подключения, а не об ошибке получении списка друзей.

2024-04-09 14:32 UTC, gbixahue commented on feature/friendsView/src/main/res/values-ru/strings.xml
> +    <string name="screen_name">Друзья</string>
Слишком абстрактное название
- screen_name_friends

2024-04-09 14:32 UTC, gbixahue commented on feature/profileView/src/main/java/com/ilya/profileview/presentation/screen/ProfileViewScreen.kt
> +            Text(text = "Back", color = LocalColorScheme.current.primaryTextColor)
Текст не из ресурсов

2024-04-09 14:32 UTC, gbixahue commented on feature/search/src/main/java/com/example/search/screen/elements/Search.kt
> +            placeholder = { Text(text = "Search") },
Текст не из ресурсов

2024-04-09 14:32 UTC, gbixahue commented on feature/search/src/main/java/com/example/search/screen/elements/Search.kt
> +fun Search(
Не совсем интуитивное название
- SearchRow
- SearchBar
- SearchFriendsInput

2024-04-09 14:32 UTC, gbixahue commented on feature/search/src/main/res/values-ru/strings.xml
> +    <string name="no_internet_error">Не удается загрузить список друзей. Проверьте подключение к интернету и попробуйте снова.</string>
Ранее описал проблему

2024-04-09 14:51 UTC, xZodiac2 commented on feature/profileView/src/main/java/com/ilya/profileview/presentation/screen/ProfileViewScreen.kt
> +            Text(text = "Back", color = LocalColorScheme.current.primaryTextColor)
Я этот экран как временную затычку сделал. Не думаю что ради неё стоит с ресурсами заморачиваться

2024-04-09 14:54 UTC, xZodiac2 commented on core/src/main/java/com/ilya/core/appCommon/AccessTokenManager.kt
> +    }
Что ты имеешь ввиду?

2024-04-09 18:35 UTC, gbixahue commented on core/src/main/java/com/ilya/core/appCommon/AccessTokenManager.kt
> +    }
У тебя метод называется **get**AccessToken и при этом он еще занимается уведомлением подписчиков при условии. Это перегружает метод и делает его использование запутанным.

Нужно подумать как распределить обязанности по методам.

2024-04-09 18:38 UTC, gbixahue commented on feature/profileView/src/main/java/com/ilya/profileview/presentation/screen/ProfileViewScreen.kt
> +            Text(text = "Back", color = LocalColorScheme.current.primaryTextColor)
Тогда нужно как-то пометить всю функцию, что она временная заглушка и в будущем будет удалена.
`// TODO: комментарий`

2024-04-09 20:12 UTC, xZodiac2 commented on core/src/main/java/com/ilya/core/appCommon/AccessTokenManager.kt
> +    private fun notifyListeners() {
Что мне надо знать чтобы решить эту проблему? У меня особо нет представлений о том как можно возможную ошибку исправить

2024-04-15 12:45 UTC, gbixahue commented on core/src/main/java/com/ilya/core/appCommon/AccessTokenManager.kt
> +    }
Дубликат getToken() ?

2024-04-15 12:45 UTC, gbixahue commented on core/src/main/java/com/ilya/core/appCommon/AccessTokenManager.kt
> +            else -> jsonAdapter.fromJson(accessTokenJsonString)
Нужно обезопасить код от IOException при `аdapter.fromJson()` т.к. при накатывании новой версии структура может измениться и старый json не распарситься.

2024-04-15 12:45 UTC, gbixahue commented on core/src/main/java/com/ilya/core/appCommon/AccessTokenManager.kt
Обратил внимание на то, что у тебя весь класс пляшет от чтения и записи в шарды - это не правильно.
Логика должна быть такая, что все обращения идут только к структуре AccessToken. 

Т.е. пока у тебя нет объекта (NULL) - любое обращение к полю accessToken провоцирует считывание json из шардов, формирование объекта и запись его в поле accessToken. В конце возвращается созданный объект. 

Если происходит изменение, ака вызов "saveAccessToken", то ты переписываешь модель и уже дополнительным действием сохраняешь json в шарды.

2024-04-15 12:45 UTC, gbixahue commented on app/src/main/java/com/ilya/vkfriends/MainActivity.kt
> +                    AccessTokenOperationsListener { token ->
лучше сделать название accessTokenListener, т.к. Observer более широкое понятие и может запутать

2024-04-15 18:28 UTC, xZodiac2 commented on core/src/main/java/com/ilya/core/appCommon/AccessTokenManager.kt
Немного не понял с логикой получения токена

2024-04-15 20:46 UTC, gbixahue commented on core/src/main/java/com/ilya/core/appCommon/AccessTokenManager.kt
Вот мое видение этого класса
```
    var accessToken: AccessToken? = restoreToken()
        set(value) {
            field = value
            updateToken(value)
        }

    private fun updateToken(accessToken: AccessToken?) {
        notifyListeners(accessToken)

        if (accessToken == null) {
            shPrefs.edit {
                remove(ACCESS_TOKEN_KEY)
                apply()
            }
        } else {
            shPrefs.edit {
                putString(ACCESS_TOKEN_KEY, jsonAdapter.toJson(accessToken))
                apply()
            }
        }
    }

    private fun restoreToken(): AccessToken? {
        val accessTokenJsonString = shPrefs.getString(ACCESS_TOKEN_KEY, "") ?: ""
        return if (accessTokenJsonString.isEmpty()) {
            null
        } else {
            try {
                jsonAdapter.fromJson(accessTokenJsonString)
            } catch (ex: java.io.IOException) {
                null
            }
        }
    }

    override fun notifyListeners(accessToken: AccessToken?) {
        synchronized(mutex) {
            listeners.forEach { it.onChange(accessToken) }
        }
    }
```

2024-12-19 22:33 UTC, merged